"""agentkit migrate — convert between AI agent context file formats.

Supported conversions:
  agents-md  → claude-md, llmstxt
  claude-md  → agents-md, llmstxt
  llmstxt    → claude-md
  all        → generate all formats from whichever source is present
"""
from __future__ import annotations

import hashlib
import re
import textwrap
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

_GEN_COMMENT = "<!-- generated by agentkit migrate -->"
_GEN_TIMESTAMP_RE = re.compile(
    r"<!-- generated by agentkit migrate -- ts:([0-9T:.+\-Z]+) hash:([a-f0-9]+) -->"
)

FORMAT_AGENTS_MD = "agents-md"
FORMAT_CLAUDE_MD = "claude-md"
FORMAT_LLMSTXT = "llmstxt"
FORMAT_ALL = "all"

KNOWN_FORMATS = {FORMAT_AGENTS_MD, FORMAT_CLAUDE_MD, FORMAT_LLMSTXT}

# Canonical filenames for each format
FORMAT_FILENAMES: dict[str, str] = {
    FORMAT_AGENTS_MD: "AGENTS.md",
    FORMAT_CLAUDE_MD: "CLAUDE.md",
    FORMAT_LLMSTXT: "llms.txt",
}

# Reverse lookup: filename → format id
FILENAME_FORMATS: dict[str, str] = {v: k for k, v in FORMAT_FILENAMES.items()}


# ---------------------------------------------------------------------------
# Data classes
# ---------------------------------------------------------------------------

@dataclass
class MigrateResult:
    source_format: str
    target_format: str
    source_path: str
    output_path: str
    content: str
    line_count: int = 0
    skipped: bool = False
    skip_reason: str = ""

    def __post_init__(self) -> None:
        if not self.line_count:
            self.line_count = len(self.content.splitlines())


@dataclass
class Section:
    """A markdown section extracted from a context file."""
    level: int          # heading level 1-6
    title: str
    body: str           # content below the heading (no trailing newline)
    raw_heading: str    # original heading line


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _make_gen_stamp(source_content: str) -> str:
    """Build the generation comment with timestamp and source hash."""
    ts = datetime.now(tz=timezone.utc).isoformat(timespec="seconds")
    h = hashlib.sha256(source_content.encode()).hexdigest()[:16]
    return f"<!-- generated by agentkit migrate -- ts:{ts} hash:{h} -->"


def _extract_gen_hash(content: str) -> Optional[str]:
    """Extract the source hash embedded in a generation comment, or None."""
    m = _GEN_TIMESTAMP_RE.search(content)
    return m.group(2) if m else None


def _source_hash(content: str) -> str:
    return hashlib.sha256(content.encode()).hexdigest()[:16]


def _parse_sections(text: str) -> list[Section]:
    """Split markdown into sections based on ## headings (level 2+)."""
    sections: list[Section] = []
    lines = text.splitlines()
    current_heading: Optional[str] = None
    current_raw: Optional[str] = None
    current_level: int = 0
    body_lines: list[str] = []

    def _flush() -> None:
        if current_heading is not None:
            sections.append(Section(
                level=current_level,
                title=current_heading,
                body="\n".join(body_lines).strip(),
                raw_heading=current_raw or "",
            ))

    for line in lines:
        m = re.match(r"^(#{1,6})\s+(.*)", line)
        if m:
            _flush()
            current_level = len(m.group(1))
            current_heading = m.group(2).strip()
            current_raw = line
            body_lines = []
        else:
            if current_heading is not None:
                body_lines.append(line)

    _flush()
    return sections


def _get_top_level_intro(text: str) -> str:
    """Extract content before the first ## heading."""
    lines = text.splitlines()
    intro: list[str] = []
    for line in lines:
        if re.match(r"^#{1,6}\s", line):
            break
        intro.append(line)
    return "\n".join(intro).strip()


def _detect_format_from_content(content: str) -> Optional[str]:
    """Heuristically detect format from file content."""
    # llms.txt starts with a title line and has URL-centric structure
    if re.match(r"^#\s+\S", content) and re.search(r"^-\s+https?://", content, re.MULTILINE):
        return FORMAT_LLMSTXT
    # AGENTS.md tends to have operational rules and identity sections
    agents_keywords = {"Session Startup", "Memory Rules", "Safety", "Autonomy", "Cron"}
    if sum(1 for kw in agents_keywords if kw.lower() in content.lower()) >= 2:
        return FORMAT_AGENTS_MD
    # CLAUDE.md tends to have project-focused sections
    claude_keywords = {"overview", "stack", "commands", "patterns", "architecture", "project"}
    if sum(1 for kw in claude_keywords if kw.lower() in content.lower()) >= 2:
        return FORMAT_CLAUDE_MD
    # Fallback heuristics based on filename hints embedded in content
    return None


def _detect_format_from_filename(filename: str) -> Optional[str]:
    name = Path(filename).name
    return FILENAME_FORMATS.get(name)


# ---------------------------------------------------------------------------
# Converters
# ---------------------------------------------------------------------------

class MigrateEngine:
    """Core engine for converting between AI agent context file formats."""

    # ------------------------------------------------------------------ #
    # Public API                                                           #
    # ------------------------------------------------------------------ #

    def detect_format(self, path: str | Path) -> Optional[str]:
        """Detect format of a file by filename then content."""
        p = Path(path)
        fmt = _detect_format_from_filename(p.name)
        if fmt:
            return fmt
        try:
            content = p.read_text(encoding="utf-8", errors="replace")
        except OSError:
            return None
        return _detect_format_from_content(content)

    def detect_source(self, directory: str | Path) -> Optional[tuple[str, Path]]:
        """Find best source file in directory. Returns (format, path) or None."""
        d = Path(directory)
        # Priority order: AGENTS.md > CLAUDE.md > llms.txt
        for fmt, fname in FORMAT_FILENAMES.items():
            p = d / fname
            if p.exists():
                return (fmt, p)
        return None

    def convert(
        self,
        source_content: str,
        source_format: str,
        target_format: str,
        source_path: str = "<source>",
        output_path: str = "<output>",
    ) -> MigrateResult:
        """Convert source_content from source_format to target_format."""
        key = f"{source_format} → {target_format}"
        dispatch: dict[str, Any] = {
            f"{FORMAT_AGENTS_MD} → {FORMAT_CLAUDE_MD}": self._agents_to_claude,
            f"{FORMAT_CLAUDE_MD} → {FORMAT_AGENTS_MD}": self._claude_to_agents,
            f"{FORMAT_AGENTS_MD} → {FORMAT_LLMSTXT}": self._agents_to_llmstxt,
            f"{FORMAT_CLAUDE_MD} → {FORMAT_LLMSTXT}": self._claude_to_llmstxt,
            f"{FORMAT_LLMSTXT} → {FORMAT_CLAUDE_MD}": self._llmstxt_to_claude,
            f"{FORMAT_LLMSTXT} → {FORMAT_AGENTS_MD}": self._llmstxt_to_agents,
        }
        if key not in dispatch:
            raise ValueError(f"Unsupported conversion: {key}")
        content = dispatch[key](source_content)
        return MigrateResult(
            source_format=source_format,
            target_format=target_format,
            source_path=source_path,
            output_path=output_path,
            content=content,
        )

    def convert_all(
        self,
        source_content: str,
        source_format: str,
        source_path: str = "<source>",
        directory: str | Path = ".",
    ) -> list[MigrateResult]:
        """Convert source to all other formats. Returns list of MigrateResult."""
        d = Path(directory)
        results: list[MigrateResult] = []
        targets = [f for f in KNOWN_FORMATS if f != source_format]
        # llmstxt → agents-md is supported but less common; keep it
        for target in targets:
            out_path = str(d / FORMAT_FILENAMES[target])
            results.append(self.convert(
                source_content=source_content,
                source_format=source_format,
                target_format=target,
                source_path=source_path,
                output_path=out_path,
            ))
        return results

    # ------------------------------------------------------------------ #
    # Staleness detection                                                  #
    # ------------------------------------------------------------------ #

    def is_stale(self, source_content: str, derived_content: str) -> bool:
        """Return True if derived file was generated from a different source hash."""
        embedded = _extract_gen_hash(derived_content)
        if embedded is None:
            # Not generated by us — can't determine staleness
            return False
        current = _source_hash(source_content)
        return embedded != current

    def get_sync_status(self, directory: str | Path) -> dict[str, str]:
        """Return sync status for all managed files in directory.

        Returns dict mapping format → "ok" | "stale" | "missing" | "unmanaged"
        """
        d = Path(directory)
        source = self.detect_source(d)
        if source is None:
            return {}
        source_fmt, source_path = source
        source_content = source_path.read_text(encoding="utf-8", errors="replace")

        status: dict[str, str] = {source_fmt: "source"}
        for fmt, fname in FORMAT_FILENAMES.items():
            if fmt == source_fmt:
                continue
            p = d / fname
            if not p.exists():
                status[fmt] = "missing"
            else:
                derived = p.read_text(encoding="utf-8", errors="replace")
                if _extract_gen_hash(derived) is None:
                    status[fmt] = "unmanaged"
                elif self.is_stale(source_content, derived):
                    status[fmt] = "stale"
                else:
                    status[fmt] = "ok"
        return status

    # ------------------------------------------------------------------ #
    # agents-md → other                                                   #
    # ------------------------------------------------------------------ #

    def _agents_to_claude(self, content: str) -> str:
        """Convert AGENTS.md to CLAUDE.md format."""
        stamp = _make_gen_stamp(content)
        sections = _parse_sections(content)
        intro = _get_top_level_intro(content)

        # Extract project name from first heading
        first_h1 = next((s for s in sections if s.level == 1), None)
        project_name = first_h1.title if first_h1 else "Project"
        # Strip "Who I Am" / identity noise from project name
        if any(kw in project_name.lower() for kw in ("who i am", "soul", "identity")):
            project_name = "Project"

        # Build CLAUDE.md structure: Overview, Stack, Commands, Patterns, Context Rules
        out_lines: list[str] = [
            f"# {project_name}",
            "",
            stamp,
            "",
        ]

        if intro and intro != f"# {project_name}":
            out_lines += [intro, ""]

        # Map AGENTS.md sections to CLAUDE.md categories
        overview_sections = []
        command_sections = []
        pattern_sections = []
        context_sections = []
        other_sections = []

        _OVERVIEW_KEYS = {"objective", "goal", "about", "overview", "purpose", "project"}
        _COMMAND_KEYS = {"command", "script", "run", "build", "test", "deploy", "install", "setup"}
        _PATTERN_KEYS = {"pattern", "style", "convention", "standard", "rule", "format", "guideline"}
        _CONTEXT_KEYS = {"memory", "session", "context", "workspace", "cron", "agent", "safety", "scope"}

        for sec in sections:
            if sec.level == 1:
                continue  # skip top-level heading
            tl = sec.title.lower()
            if any(k in tl for k in _OVERVIEW_KEYS):
                overview_sections.append(sec)
            elif any(k in tl for k in _COMMAND_KEYS):
                command_sections.append(sec)
            elif any(k in tl for k in _PATTERN_KEYS):
                pattern_sections.append(sec)
            elif any(k in tl for k in _CONTEXT_KEYS):
                context_sections.append(sec)
            else:
                other_sections.append(sec)

        def _emit_section(heading: str, secs: list[Section]) -> None:
            if not secs:
                return
            out_lines.append(f"## {heading}")
            out_lines.append("")
            for sec in secs:
                if sec.level > 2:
                    out_lines.append(f"{'#' * sec.level} {sec.title}")
                else:
                    out_lines.append(f"### {sec.title}")
                out_lines.append("")
                if sec.body:
                    out_lines.append(sec.body)
                    out_lines.append("")

        _emit_section("Overview", overview_sections)
        _emit_section("Commands", command_sections)
        _emit_section("Patterns & Conventions", pattern_sections)
        _emit_section("Context & Workspace", context_sections)
        if other_sections:
            _emit_section("Additional Context", other_sections)

        return "\n".join(out_lines).rstrip() + "\n"

    # ------------------------------------------------------------------ #
    # claude-md → other                                                   #
    # ------------------------------------------------------------------ #

    def _claude_to_agents(self, content: str) -> str:
        """Convert CLAUDE.md to AGENTS.md format."""
        stamp = _make_gen_stamp(content)
        sections = _parse_sections(content)
        intro = _get_top_level_intro(content)

        first_h1 = next((s for s in sections if s.level == 1), None)
        project_name = first_h1.title if first_h1 else "Project"

        out_lines: list[str] = [
            f"# AGENTS.md — {project_name}",
            "",
            stamp,
            "",
        ]

        if intro:
            out_lines += [intro, ""]

        # Map CLAUDE.md sections to AGENTS.md operational categories
        for sec in sections:
            if sec.level == 1:
                continue
            out_lines.append(f"{'#' * sec.level} {sec.title}")
            out_lines.append("")
            if sec.body:
                out_lines.append(sec.body)
                out_lines.append("")

        return "\n".join(out_lines).rstrip() + "\n"

    # ------------------------------------------------------------------ #
    # → llmstxt                                                            #
    # ------------------------------------------------------------------ #

    def _agents_to_llmstxt(self, content: str) -> str:
        """Convert AGENTS.md to llms.txt format."""
        return self._md_to_llmstxt(content, source_hint="AGENTS.md")

    def _claude_to_llmstxt(self, content: str) -> str:
        """Convert CLAUDE.md to llms.txt format."""
        return self._md_to_llmstxt(content, source_hint="CLAUDE.md")

    def _md_to_llmstxt(self, content: str, source_hint: str = "") -> str:
        """Generic markdown → llms.txt conversion."""
        stamp = _make_gen_stamp(content)
        sections = _parse_sections(content)
        intro = _get_top_level_intro(content)

        first_h1 = next((s for s in sections if s.level == 1), None)
        project_name = first_h1.title if first_h1 else "Project"

        # Build description from intro or first body section
        description = intro
        if not description:
            first_body = next((s for s in sections if s.level > 1 and s.body), None)
            if first_body:
                description = first_body.body.splitlines()[0] if first_body.body else ""
        description = description[:300].strip()

        out_lines: list[str] = [
            f"# {project_name}",
            "",
            stamp,
            "",
        ]
        if description:
            out_lines += [f"> {description}", ""]

        # Emit h2 sections as llms.txt sections with inline content links
        for sec in sections:
            if sec.level != 2:
                continue
            out_lines.append(f"## {sec.title}")
            out_lines.append("")
            if sec.body:
                # Wrap body as a summary paragraph
                wrapped = textwrap.fill(sec.body.replace("\n", " "), width=80)
                out_lines.append(wrapped)
            out_lines.append("")

        # Note the source hint
        out_lines += [
            "## Source",
            "",
            f"- Generated from: {source_hint}",
            "",
        ]

        return "\n".join(out_lines).rstrip() + "\n"

    # ------------------------------------------------------------------ #
    # llmstxt → other                                                      #
    # ------------------------------------------------------------------ #

    def _llmstxt_to_claude(self, content: str) -> str:
        """Convert llms.txt to CLAUDE.md format."""
        stamp = _make_gen_stamp(content)
        sections = _parse_sections(content)
        intro = _get_top_level_intro(content)

        first_h1 = next((s for s in sections if s.level == 1), None)
        project_name = first_h1.title if first_h1 else "Project"

        out_lines: list[str] = [
            f"# {project_name}",
            "",
            stamp,
            "",
        ]

        if intro:
            intro_clean = re.sub(r"^>?\s*", "", intro, flags=re.MULTILINE).strip()
            if intro_clean:
                out_lines += [intro_clean, ""]

        for sec in sections:
            if sec.level == 1:
                continue
            out_lines.append(f"## {sec.title}")
            out_lines.append("")
            if sec.body:
                out_lines.append(sec.body)
                out_lines.append("")

        return "\n".join(out_lines).rstrip() + "\n"

    def _llmstxt_to_agents(self, content: str) -> str:
        """Convert llms.txt to AGENTS.md format."""
        stamp = _make_gen_stamp(content)
        sections = _parse_sections(content)
        intro = _get_top_level_intro(content)

        first_h1 = next((s for s in sections if s.level == 1), None)
        project_name = first_h1.title if first_h1 else "Project"

        out_lines: list[str] = [
            f"# AGENTS.md — {project_name}",
            "",
            stamp,
            "",
        ]

        if intro:
            out_lines += [intro.strip(), ""]

        for sec in sections:
            if sec.level == 1:
                continue
            out_lines.append(f"## {sec.title}")
            out_lines.append("")
            if sec.body:
                out_lines.append(sec.body)
                out_lines.append("")

        return "\n".join(out_lines).rstrip() + "\n"


# Keep a module-level type alias for type checkers
from typing import Any  # noqa: E402 (keep at end to avoid circular)
